### ISSUE TITLE
handle mobile users

### ISSUE THREAD

**Issue by ryan-zhu-music** [SlimeScholars/slime-scholars#19]

**Comment by jiayishen21** [comment]
Get done by Feb. 10.

1. Do not allow mobile users to go into play or courses (for now)
2. Fix testimonials on mobile
3. Fix signup, login, etc. for mobile

**Comment by jiayishen21** [comment]
Updated implementation of mobile noperms, also checked over login and register (it should be fine for now, also Anthony should be finishing his updates on OAuth and styling login).
